datatop: Fix out_dir array empty content verification
 * Introduced by commit:
    "datatop: add support to capture ip table stats

 * Fixes the following error:
    vendor/qcom/opensource/dataservices/datatop/src/datatop.c:203:20:
    error: address of array 'usr_cl_opts.out_dir' will always
    evaluate to 'true' [-Werror,-Wpointer-bool-conversion]

Change-Id: I19ed8082b1a811451a73a571bc1a4076c20d454e